import type { QuizQuestion, Subject } from '@/types';

export const MATH_QUESTIONS: QuizQuestion[] = [
  {
    id: 'm1',
    subject: 'Math',
    text: 'What is 2 + 2?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'calculation numbers',
    options: [ { id: 'm1a1', text: '3' }, { id: 'm1a2', text: '4' }, { id: 'm1a3', text: '5' }, { id: 'm1a4', text: '6' } ],
    correctAnswerId: 'm1a2',
  },
  {
    id: 'm2',
    subject: 'Math',
    text: 'What is 10 - 3?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'subtraction arithmetic',
    options: [ { id: 'm2a1', text: '6' }, { id: 'm2a2', text: '7' }, { id: 'm2a3', text: '8' }, { id: 'm2a4', text: '9' } ],
    correctAnswerId: 'm2a2',
  },
  {
    id: 'm3',
    subject: 'Math',
    text: 'What is 5 * 3?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'multiplication numbers',
    options: [ { id: 'm3a1', text: '12' }, { id: 'm3a2', text: '15' }, { id: 'm3a3', text: '18' }, { id: 'm3a4', text: '20' } ],
    correctAnswerId: 'm3a2',
  },
  {
    id: 'm4',
    subject: 'Math',
    text: 'What is 12 / 4?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'division problem',
    options: [ { id: 'm4a1', text: '2' }, { id: 'm4a2', text: '3' }, { id: 'm4a3', text: '4' }, { id: 'm4a4', text: '6' } ],
    correctAnswerId: 'm4a2',
  },
  {
    id: 'm5',
    subject: 'Math',
    text: 'How many sides does a triangle have?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'geometric shapes',
    options: [ { id: 'm5a1', text: '2' }, { id: 'm5a2', text: '3' }, { id: 'm5a3', text: '4' }, { id: 'm5a4', text: '5' } ],
    correctAnswerId: 'm5a2',
  },
  {
    id: 'm6',
    subject: 'Math',
    text: 'What is the square root of 9?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'math roots',
    options: [ { id: 'm6a1', text: '2' }, { id: 'm6a2', text: '3' }, { id: 'm6a3', text: '4' }, { id: 'm6a4', text: '81' } ],
    correctAnswerId: 'm6a2',
  },
  {
    id: 'm7',
    subject: 'Math',
    text: 'If a square has a side length of 5 units, what is its area?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'area calculation',
    options: [ { id: 'm7a1', text: '10 sq units' }, { id: 'm7a2', text: '20 sq units' }, { id: 'm7a3', text: '25 sq units' }, { id: 'm7a4', text: '30 sq units' } ],
    correctAnswerId: 'm7a3',
  },
  {
    id: 'm8',
    subject: 'Math',
    text: 'What is 20% of 100?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'percentage math',
    options: [ { id: 'm8a1', text: '10' }, { id: 'm8a2', text: '20' }, { id: 'm8a3', text: '25' }, { id: 'm8a4', text: '50' } ],
    correctAnswerId: 'm8a2',
  },
  {
    id: 'm9',
    subject: 'Math',
    text: 'What is the next number in the sequence: 2, 4, 6, 8, ...?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'number sequence',
    options: [ { id: 'm9a1', text: '9' }, { id: 'm9a2', text: '10' }, { id: 'm9a3', text: '11' }, { id: 'm9a4', text: '12' } ],
    correctAnswerId: 'm9a2',
  },
  {
    id: 'm10',
    subject: 'Math',
    text: 'How many degrees are in a right angle?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'angle geometry',
    options: [ { id: 'm10a1', text: '45' }, { id: 'm10a2', text: '90' }, { id: 'm10a3', text: '180' }, { id: 'm10a4', text: '360' } ],
    correctAnswerId: 'm10a2',
  },
];

export const ENGLISH_QUESTIONS: QuizQuestion[] = [
  {
    id: 'e1',
    subject: 'English',
    text: 'Which of these is a noun?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'books library',
    options: [ { id: 'e1a1', text: 'Run' }, { id: 'e1a2', text: 'Quickly' }, { id: 'e1a3', text: 'Apple' }, { id: 'e1a4', text: 'Beautiful' } ],
    correctAnswerId: 'e1a3',
  },
  {
    id: 'e2',
    subject: 'English',
    text: 'What is the past tense of "go"?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'grammar verbs',
    options: [ { id: 'e2a1', text: 'Goed' }, { id: 'e2a2', text: 'Went' }, { id: 'e2a3', text: 'Gone' }, { id: 'e2a4', text: 'Going' } ],
    correctAnswerId: 'e2a2',
  },
  {
    id: 'e3',
    subject: 'English',
    text: 'Which punctuation mark is used to end a question?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'punctuation writing',
    options: [ { id: 'e3a1', text: '.' }, { id: 'e3a2', text: ',' }, { id: 'e3a3', text: '!' }, { id: 'e3a4', text: '?' } ],
    correctAnswerId: 'e3a4',
  },
  {
    id: 'e4',
    subject: 'English',
    text: 'What is a synonym for "happy"?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'vocabulary words',
    options: [ { id: 'e4a1', text: 'Sad' }, { id: 'e4a2', text: 'Angry' }, { id: 'e4a3', text: 'Joyful' }, { id: 'e4a4', text: 'Tired' } ],
    correctAnswerId: 'e4a3',
  },
  {
    id: 'e5',
    subject: 'English',
    text: 'Identify the adjective in the sentence: "The red car is fast."',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sentence structure',
    options: [ { id: 'e5a1', text: 'Car' }, { id: 'e5a2', text: 'Red' }, { id: 'e5a3', text: 'Is' }, { id: 'e5a4', text: 'Fast' } ],
    correctAnswerId: 'e5a2', // Or 'Fast', adjectives describe nouns. Let's pick 'Red'.
  },
  {
    id: 'e6',
    subject: 'English',
    text: 'Which word is a pronoun: "She gave the book to him."',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'grammar pronouns',
    options: [ { id: 'e6a1', text: 'Gave' }, { id: 'e6a2', text: 'Book' }, { id: 'e6a3', text: 'She' }, { id: 'e6a4', text: 'To' } ],
    correctAnswerId: 'e6a3',
  },
  {
    id: 'e7',
    subject: 'English',
    text: 'What is the plural of "mouse"?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'plurals grammar',
    options: [ { id: 'e7a1', text: 'Mouses' }, { id: 'e7a2', text: 'Mice' }, { id: 'e7a3', text: 'Mousees' }, { id: 'e7a4', text: 'Meese' } ],
    correctAnswerId: 'e7a2',
  },
  {
    id: 'e8',
    subject: 'English',
    text: 'Complete the sentence: "I ___ to the store yesterday."',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'verb tense',
    options: [ { id: 'e8a1', text: 'go' }, { id: 'e8a2', text: 'goes' }, { id: 'e8a3', text: 'went' }, { id: 'e8a4', text: 'going' } ],
    correctAnswerId: 'e8a3',
  },
  {
    id: 'e9',
    subject: 'English',
    text: 'Which of these is a conjunction: "I like apples ___ bananas."',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'grammar conjunctions',
    options: [ { id: 'e9a1', text: 'but' }, { id: 'e9a2', text: 'or' }, { id: 'e9a3', text: 'and' }, { id: 'e9a4', text: 'so' } ],
    correctAnswerId: 'e9a3', // 'or' and 'but' also work, but 'and' is a common example
  },
  {
    id: 'e10',
    subject: 'English',
    text: 'What is an antonym for "big"?',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'opposites vocabulary',
    options: [ { id: 'e10a1', text: 'Large' }, { id: 'e10a2', text: 'Huge' }, { id: 'e10a3', text: 'Small' }, { id: 'e10a4', text: 'Giant' } ],
    correctAnswerId: 'e10a3',
  },
];

export const getQuestionsBySubject = (subject: Subject): QuizQuestion[] => {
  if (subject === 'Math') return MATH_QUESTIONS.slice(0, 10);
  if (subject === 'English') return ENGLISH_QUESTIONS.slice(0, 10);
  return [];
};
